TestShell_Excutor/TestShell_Excutor.vcxproj.filters
Merge Conflict 났을 때 filter file을 잘못 고쳐서 수정해서 올립니다.
=> Fix Filter file

TestShell_Excutor/TS_function.cpp, TestShell_Excutor/TS_function_test.cpp
TS_function read 함수에 대한 unittest 와 구현입니다.
=> TS_function Read TDD

TestShell_Excutor/TS_function.cpp, TestShell_Excutor/TS_function_test.cpp, TestShell_Excutor/TestShell_Excutor.vcxproj, TestShell_Excutor/TestShell_Excutor.vcxproj.filters
Conflict해결하고 최종 확인 후 PR합니다.
[add] update write function for NoWriteOutOfRangeLBA TCs
[add] NoWriteOutOfRangeLBA TCs
[add] feature for Write basic TC
[add] Write basic TC
=> ADD Feature/TS_Write

TestShell_Excutor/InvalidCmd_test.cpp
=> [Add] Invalid Command Case UT

TestShell_Excutor/TS_function_test.cpp
TS_function_test내 TC들에 대한 Fixture처리 입니다.
=> [refactoring] add SSDFixture for TS_function

TestShell_Excutor/InvalidCmd_test.cpp
Check command parameter num UT PASS
=> [ADD] Check command parameter num UT

SSD_Excutor/SSD_Excutor.vcxproj, SSD_Excutor/command_parser.cpp, SSD_Excutor/command_parser_test.cpp
[add] ssd command parser ut 추가
command parset에 대해서 UT 추가 (Red Case)
=> [add] ssd command parser ut 추가

TestShell_Excutor/CommandParser.cpp, TestShell_Excutor/CommandParser.h, TestShell_Excutor/InvalidCmd_test.cpp
add check LBA UT 
- case of string
- range check( 0~99 )
=> [add] check lba UT & feature

SSD_Excutor/write.cpp, SSD_Excutor/write_test.cpp
Write UT가 동작하도록 Write 개발
동작 논리
map 이라는 배열을 가지고 있음.
map에 특정 lba index로 접근해서 value 수정
수정 후 map만큼을 모두 ssd_nand.txt에 write
=> [add] Write execute 함수 구현 (Green Case)

TestShell_Excutor/TS_function.cpp, TestShell_Excutor/TS_function_test.cpp
[refactoring] fullwrite
[add] modify fullwrite() for fullwrite TC Normal Pass
[add] fullwrite TC Normal Pass
=> add fullwrite function and TC Normal Pass

SSD_Excutor/write.cpp, SSD_Excutor/write_test.cpp
SSD Write Refactorying
Write UT TS 이름 변경
Write 함수 Refactoring
=> [Refactor] SSD Write Refactorying

TestShell_Excutor/TS_function.cpp
Parser 연결을 위해 TS_function 에 Dummy function interface 를 추가했습니다.
=> Dummy function interface for TS_function

SSD_Excutor/read_test.cpp
ssd read 동작에 대한 UT 추가하였습니다.
write 동작에 의존성이 있는 UT는 우선 DISABLED_ 처리 하였습니다.
=> [add] SSD Read UT 추가 (Red)

SSD_Excutor/SSD_Excutor.vcxproj, SSD_Excutor/SSD_Excutor.vcxproj.filters, SSD_Excutor/command_parser.cpp, SSD_Excutor/command_parser_test.cpp, SSD_Excutor/main.cpp, SSD_Excutor/read_test.cpp, SSD_Excutor/ssd.cpp, SSD_Excutor/ssd_test.cpp, SSD_Excutor/write_test.cpp
ssd class에 run 추가 (exe파일 release시에 사용할 함수)
CommandParser에 대해서 Mock을 만들어서 CommandParser 개발 안되었어도 테스트 가능하도록 UT 추가
=> [add] SSD Class에 대한 UT 추가 및 run 함수 추가 (Red, Green Case)

TestShell_Excutor/TS_function.cpp, TestShell_Excutor/TS_function_test.cpp
TestScript 에서 내부적으로 사용하는 ReadCompare 함수입니다.
lba 와 written data 값을 입력으로 받아서  lba 를 read 한 값이 writtendata 와 같으면 true 틀리면 fail 입니다.
=> TS_function  ReadCompare 함수 구현

SSD_Excutor/read_test.cpp, SSD_Excutor/write_test.cpp
=> [Refactor] Write UT Refactoring

SSD_Excutor/ssd_test.cpp, SSD_Excutor/write_test.cpp
SSD UT와 Write UT Refactoring
Fixture 사용
SetUp 사용
TearDown 사용
=> [refactor] SSD UT와 Write UT Refactoring

SSD_Excutor/read.cpp
SSD read에 대해 함수 level에서 refactoring을 진행하였습니다
- 공개가 필요없는 logic은 private method로 감추었습니다.
- output file에 대한 관리는 우선 Read에서 담당하기로 하여 output file에 원하는 text를 write하는 method를 public으로 공개하였습니다.
=> [refactor]ssd read

SSD_Excutor/ssd_test.cpp
=> [fix] 파일 입출력 꼬이는 부분 수정

SSD_Excutor/main.cpp
exe파일 release해서 수행하게 될 때 타게 될 코드 추가
=> [add] main 함수에 ssd 객체 생성하고 run할 수 있도록 추가

SSD_Excutor/command_parser.cpp, SSD_Excutor/command_parser.h
LBA와 value를 unsigned int 형으로 변환하는 함수를 만들어 Refactoring 했습니다.
=> [Refactor] Feature/ssd command parser

SSD_Excutor/command_parser.cpp, SSD_Excutor/command_parser.h, SSD_Excutor/command_parser_test.cpp
-BugFix : Command parser 에서 Argument 0 = ssd.exe 이므로 Argument1 부터 Command로 인식하도록 수정
-Refactor: Command Parser UT
=> [Fix&Refactor] CommandParsing bug fix & Refactor UT

SSD_Excutor/SSD_Excutor.vcxproj, SSD_Excutor/SSD_Excutor.vcxproj.filters, SSD_Excutor/command_interface.cpp, SSD_Excutor/command_interface.h, SSD_Excutor/main.cpp, SSD_Excutor/read.cpp, SSD_Excutor/ssd.cpp, SSD_Excutor/ssd_test.cpp, SSD_Excutor/write.cpp, SSD_Excutor/write_test.cpp
command에 대해서 factory 구성 및 command pattern 적용
nand.txt가 계속 새로워지는 현상 수정
=> [refactor | fix] command에 대해서 factory 구성 및 command pattern 적용

SSD_Excutor/write.cpp
long int로 변환하는 함수를 unsigned int로 변환하도록 수정
=> [fix] long int로 변환하는 함수를 unsigned int로 변환하도록 수정

TestShell_Excutor/TS_function.cpp
writeReadAging 에 대한 구현입니다.
Random 에 대한 Mocking 이 어려워서 UT 는 제외하고 개발진행했습니다.
=> 3_writeReadAging 

SSD_Excutor/FileUtil.cpp, SSD_Excutor/command_interface.cpp, SSD_Excutor/command_interface.h, SSD_Excutor/read.cpp, SSD_Excutor/ssd.cpp
output file에 대한 관리를 Read class에서 하고 있었는데, output file 삭제를 비롯한 동작이 다른 class에서도 필요하여 FileUtil class를 도입하였습니다.
FileUtil class 도입으로 발생한 중복 코드를 삭제하였습니다.
=> [refactoring]introduce FileUtil and delete duplicate codes

SSD_Excutor/SSD_Excutor.vcxproj, SSD_Excutor/SSD_Excutor.vcxproj.filters, SSD_Excutor/erase.cpp, SSD_Excutor/erase_test.cpp
=> SSD 추가 기능 개발을 위한 file 추가 건 입니다.

TestShell_Excutor/ShellErase.h, TestShell_Excutor/ShellFlush.h, TestShell_Excutor/ShellFullRead.h, TestShell_Excutor/ShellFullWrite.h, TestShell_Excutor/ShellRead.h, TestShell_Excutor/ShellTestScenarios.h, TestShell_Excutor/ShellWrite.h, TestShell_Excutor/TestShell_Excutor.vcxproj, TestShell_Excutor/TestShell_Excutor.vcxproj.filters
[add] new files to order to apply design pattern
This patch addes new files for each basic function and TestScenarios.
Each file will be refactored from CommandParser.cpp and TS_function.cpp
*ShellErase.cpp
*ShellErase.h
*ShellFlush.cpp
*ShellFlush.h
*ShellFullRead.cpp
*ShellFullRead.h
*ShellFullWrite.cpp
*ShellFullWrite.h
*ShellRead.cpp
*ShellRead.h
*ShellTestScenarios.cpp
*ShellTestScenarios.h
*ShellWrite.cpp
*ShellWrite.h
=> [add] new files to order to apply design pattern

.github/PULL_REQUEST_TEMPLATE.md
This file supports automation to clear documenting BOYSCOUT pull requests.
* Pull Request Template
* Title (Mandatory)
- [fix/add/refactor] 간결하게 (80자미만) PR 제목을 기입해주세요.
* Which solution? (Mandatory)
* Changes : What(feature/bugfix) -> Why(optional)
- 변경사항을 두괄실으로 요약해 기입해주세요.
* To Reviewer(optional)
=> [add] introcude pull request template documenting

SSD_Excutor/command_parser.cpp, SSD_Excutor/command_parser.h, SSD_Excutor/command_parser_test.cpp, SSD_Excutor/read.cpp
SSD Command Parser에 Erase command 추가
LBA 유효성 체크
SIZE 유효성 체크
LBA+SIZE range 체크
=> [add]Feature/ssd erase cmd

SSD_Excutor/command_parser.cpp, SSD_Excutor/command_parser.h, SSD_Excutor/command_parser_test.cpp
- [add/Refactor]Feature/ssd flush cmd
- Add flush Command
- 가독성을 위해 10진수 number 체크하는 부분과 16진수인지 체크하는 부분을 Function 화 했습니다.
=> [add/Refactor] Feature/ssd flush cmd

SSD_Excutor/SSD_Excutor.vcxproj, TestShell_Excutor/TestShell_Excutor.vcxproj
- [add] c++ 버전을 14에서 17로 업그레이드
- c++ 버전을 14에서 17로 업그레이드
- 
=> [add] c++ 버전을 14에서 17로 업그레이드

TestShell_Excutor/CommandParser.cpp, TestShell_Excutor/CommandParser.h, TestShell_Excutor/InvalidCmd_test.cpp
- [add]Feature/shell erase cmd invalid cmd
- Add  Erase Command Invalid Check 
=> [add]Feature/shell erase cmd invalid cmd

TestShell_Excutor/CommandParser.h
- [fix/add/refactor] 간결하게 (80자미만) PR 제목을 기입해주세요.
- UT에서 사용하는 함수 Private 설정으로 변경되어 Build Error
- public으로 함수위치 수정함
=> [bugfix]builderror

SSD_Excutor/SSD_Excutor.vcxproj, SSD_Excutor/SSD_Excutor.vcxproj.filters, SSD_Excutor/command_buffer_manager.cpp, SSD_Excutor/command_buffer_manager.h, SSD_Excutor/command_factory.cpp, SSD_Excutor/command_factory.h, SSD_Excutor/command_parser.h, SSD_Excutor/flush_test.cpp, SSD_Excutor/ssd.cpp, SSD_Excutor/write.cpp, SSD_Excutor/write.h
- [refactor] CommandBufferManager, Write, Flush, SSD Refactoring
- CommandBufferManager, Write, Flush, SSD Refactoring
=> [refactor] CommandBufferManager, Write, Flush, SSD Refactoring

TestShell_Excutor/ShellFlush.cpp
- [fix/add/refactor] 간결하게 (80자미만) PR 제목을 기입해주세요.
- [* ] TestShell
- excute 시 flush를 call하도록 수정
=> [fix] add calling SSD's flush in Flush::excute

SSD_Excutor/SSD_Excutor.vcxproj.filters, SSD_Excutor/command_buffer_manager.cpp, SSD_Excutor/command_buffer_manager.h, SSD_Excutor/command_buffer_manager_test.cpp, SSD_Excutor/flush_test.cpp, SSD_Excutor/ssd.cpp
- [add] 일반적인 Command Buffer 동작 Enable.
- 일반적인 Command Buffer 동작 Enable
- CommandBufferManager UT 추가
- Command Buffer Enable 해서 SSDTS UT Fail 됨. 참고 바람
=> [add] 일반적인 Command Buffer 동작 Enable

TestShell_Excutor/ShellErase.cpp, TestShell_Excutor/ShellErase.h, TestShell_Excutor/ShellEraseRange.cpp, TestShell_Excutor/ShellEraseRange.h, TestShell_Excutor/ShellFlush.cpp, TestShell_Excutor/ShellFlush.h, TestShell_Excutor/ShellFullRead.cpp, TestShell_Excutor/ShellFullRead.h, TestShell_Excutor/ShellFullWrite.cpp, TestShell_Excutor/ShellFullWrite.h, TestShell_Excutor/ShellLogger.cpp, TestShell_Excutor/ShellLogger.h, TestShell_Excutor/ShellRead.cpp, TestShell_Excutor/ShellRunner.cpp, TestShell_Excutor/ShellRunner.h, TestShell_Excutor/ShellTestScenarios.cpp, TestShell_Excutor/ShellTestScenarios.h, TestShell_Excutor/ShellWrite.cpp, TestShell_Excutor/ShellWrite.h
- [fix/add/refactor] 간결하게 (80자미만) PR 제목을 기입해주세요.
- 기존 Logger 를 Logger::getInstance로 singleton refactoring.
=> [refactor] use Logger.getinstance() as Singleton

SSD_Excutor/SSDHelper.cpp, SSD_Excutor/SSDHelper.h, SSD_Excutor/command_buffer_manager.cpp, SSD_Excutor/command_buffer_manager_test.cpp, SSD_Excutor/flush_test.cpp, SSD_Excutor/ssd_test.cpp, SSD_Excutor/write_test.cpp
- [refactor] SSDExecutor 프로젝트 내 모든 class에 대해서 refactoring
- unit test하는 과정에서 nand.txt나 buffer 직접 접근해야 하는 경우에 SSDHelper를 이용하도록 수정
- SSDHelper는 UT 목적으로만 사용
=> [refactor] SSDExecutor 프로젝트 내 모든 class에 대해서 refactoring

SSD_Excutor/command_buffer_manager.cpp
- [fix] read하면 buffer 삭제되는 부분 수정
- read하면 buffer 삭제되는 부분 수정
=> [fix] read하면 buffer 삭제되는 부분 수정

BoyScoutDemo1-1DayBasic.lst, BoyScoutDemo2-1DayComplex.lst, BoyScoutDemo3-3DayExtension.lst, BoyScoutDemo5-TScenarioLoop.lst, SSD_Project_BoyScout.sln
- [add] upload default demo script files
- This files will be used when presentation demo easily. Please note that BoyScoutDemo4-3DayCommandBuffer.lst should be updated by commandbuffer owner.
- 5개의 파일을 1day/3day/복합/commandbuffer/TestScript로 만들어 놓고 demo시에 활용하려고 합니다.
=> [add] upload default demo script files

TestShell_Excutor/TestShell_Excutor.vcxproj, TestShell_Excutor/TestShell_Excutor.vcxproj.filters
- [fix] fixed TestShell project load failure and filter issue
- 프로젝트 로드 및 필터이슈(폴더사라짐) 이슈 해결입니다.
=> [fix] fixed TestShell project load failure and filter issue

.github/PULL_REQUEST_TEMPLATE.md
1. link 공유 시 Changes가 바로 보이도록 위치 변경합니다.
2. Title은 중복이라 제거 합니다.
=> [refactor] change PR_TEMPLATE to show what's first

SSD_Excutor/command_buffer_manager.cpp, SSD_Excutor/command_buffer_manager.h
- max lba case에 대한 buffer optimize 불량 수정
=> [fix] max lba case에 대한 buffer optimize 불량 수정

SSD_Excutor/command_buffer_manager.cpp, SSD_Excutor/command_buffer_manager.h
- optimize Buffer 불량 제거를 위한 논리 수정
=> [fix] optimize Buffer 불량 제거를 위한 논리 수정

SSD_Excutor/command_buffer_manager.cpp, SSD_Excutor/command_buffer_manager.h
=> [refactor] optimize buffer 함수 refac

TestShell_Excutor/ShellLogger.h
=> [refactor] remove useless comment

TestShell_Excutor/ShellCommand_test.cpp, TestShell_Excutor/ShellEraseRange.cpp, TestShell_Excutor/ShellFileUtil.cpp, TestShell_Excutor/ShellRead.cpp, TestShell_Excutor/ShellWrite.cpp
- TestShell등 Build시 Warning 제거
=> [refactor] remove warning on build

TestShell_Excutor/ShellErase.cpp
=> [fix] wrong condition
